### ISSUE TITLE
less compilation with css-modules

### ISSUE THREAD

**Issue by sharmasourabh** [jonycheung/deadsimple-less-watch-compiler#83]
**Which version are you using (less-watch-compiler --version to find out)?**: 1.13.0

**Is the issue reproducible after updating to the latest version ( npm update less-watch-compiler)?** Yes

**Describe the bug**
Does not work with css-modules.

```css
.aClass {
  width: 100%;
  display: flex;

  :global {
    .bClass {
      font-size: 14px;
    }
  }
}
```

gets compiled into

```css
.aClass{
  width: 100%;
  display: flex;
}

.aClass :global .bClass {
  font-size: 14px;
}
```

Could you please share how to handle scoped variables?
